name: 改善・追加提案
description: 指標、自治体、UI、ドキュメントなどの提案
title: "[Proposal] "
labels: ["proposal"]
body:
  - type: dropdown
    attributes:
      label: 種別
      options: ["指標追加", "自治体追加", "UI改善", "ドキュメント改善", "その他"]
    validations: { required: true }
  - type: textarea
    attributes: { label: 解決したい課題 }
    validations: { required: true }
  - type: textarea
    attributes: { label: 提案内容 }
    validations: { required: true }
  - type: input
    attributes: { label: 関連するデータソースURL }
